# Default values for short-url-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: bachdangtuan/short-url-dev
  pullPolicy: IfNotPresent
  tag: "1.0.4"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels:
  app: short-url-dev

service:
  name: short-url-svc
  type: ClusterIP
  port: 3000
  protocol: TCP

ingress:
  enabled: false
  className: "nginx"
  annotations:
    {}
  hosts:
    host: zurl-short-prod.ivirse.com
    paths:
    path: /
    pathType: ImplementationSpecific
  tls: []

resources:
  {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http