replicaCount: 3

image:
  repository: bachdangtuan/short-url-prod
  pullPolicy: IfNotPresent
  tag: "1.0.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels:
  app: short-url-prod

service:
  name: short-url-svc
  type: ClusterIP
  port: 3000
  protocol: TCP

ingress:
  enabled: false
  className: "nginx"
  annotations:
    {}
  hosts:
    host: zurl-short-prod.ivirse.com
    paths:
    path: /
    pathType: ImplementationSpecific
  tls: []

resources:
  {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http