replicaCount: 2
image:
  repository: bachdangtuan/short-url-dev
  pullPolicy: IfNotPresent
  tag: "1.0.4"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels:
  app: short-url-dev

service:
  name: short-url-svc-dev
  type: ClusterIP
  port: 3000
  protocol: TCP

ingress:
  enabled: false
  className: "nginx"
  annotations:
    {}
  hosts:
    host: zurl-short-dev.ivirse.com
    paths:
    path: /
    pathType: ImplementationSpecific
  tls: []
resources:
  {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http