replicaCount: 3

image:
  repository: bachdangtuan/short-url-prod
  pullPolicy: IfNotPresent
  tag: "1.0.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels:
  app: short-url-prod

service:
  name: short-url-svc-production
  type: ClusterIP
  port: 3000
  protocol: TCP

resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# HPA
hpa:
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: short-url-app
