# Default values for short-url-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: bachdangtuan/short-url-dev
  pullPolicy: IfNotPresent
  tag: "1.0.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels:
  app: short-url-dev

# podSecurityContext:
#   {}

# securityContext:
#   {}


service:
  name: short-url-svc-dev
  type: ClusterIP
  port: 3000
  protocol: TCP

ingress:
  enabled: false
  className: "nginx"
  annotations:
    {}
  hosts:
    host: short-url-dev.rancher.local
    paths:
    path: /
    pathType: ImplementationSpecific
  tls: []

resources:
  {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80

# volumes: []
# # - name: foo
# #   secret:
# #     secretName: mysecret
# #     optional: false

# # Additional volumeMounts on the output Deployment definition.
# volumeMounts: []
# # - name: foo
# #   mountPath: "/etc/foo"
# #   readOnly: true

# nodeSelector: {}

# tolerations: []

# affinity: {}
