apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
spec:
  ingressClassName: {{ .Values.ingress.className}}
  rules:
  - host: {{ .Values.ingress.hosts.host}}
    http:
      paths:
      - path: {{ .Values.ingress.hosts.path}}
        pathType: {{ .Values.ingress.hosts.pathType}}
        backend:
          service:
            name: {{ .Values.service.name}}
            port:
              number: {{ .Values.service.port}}
