apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name}}
spec:
  type: {{ .Values.service.type}}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: {{ .Values.service.protocol}}
      name: http
  selector:
    app: {{ .Values.podLabels.app}}
