apiVersion: v1
kind: Service
metadata:
  name: short-url-svc
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.podLabels.app}}
